services:
  db:
    image: postgres:latest
    volumes: 
      - ./data:/var/lib/postgresql
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_DB=handson
     - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"